FROM registry.redhat.io/rhel10/rhel-bootc:latest

# Build Metadata Argument
ARG GIT_COMMIT=unknown

# Install Packages
RUN dnf -y install httpd virtio-win qemu-guest-agent \
 greenboot greenboot-default-health-checks \
 && dnf update -y && dnf clean all

# Set up Greenboot (RHEL helth check framework)
RUN mkdir -p /etc/greenboot/check/required.d/
RUN cat <<EOF > /etc/greenboot/check/required.d/01_httpd_check.sh
#!/bin/bash
# Check if Apache is responding on localhost
curl -f http://localhost/ || exit 1
EOF
RUN chmod +x /etc/greenboot/check/required.d/01_httpd_check.sh

# Bake Metadata into the image
RUN echo "Build Date: $(date)" > /etc/image-build-info && \
    echo "Git Commit: $GIT_COMMIT" >> /etc/image-build-info

# 1. Create Web Root
RUN echo "<h1>Hello from RHEL Image Mode</h1>" > /var/www/html/index.html

# 2. Enable Service
RUN systemctl enable httpd

# 3. Set Password (for demo)
RUN echo "root:*****" | chpasswd
