---
- name: Enterprise RHEL 10 Image Mode Deployment
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/secrets.yml
  vars:
    # Image Configuration
    containerfile_name: "ContainerFile"
    quay_repo: "isrealvarela"
    image_name: "rhel10-bootc"
    full_image_path: "quay.io/{{ quay_repo }}/{{ image_name }}:latest"
    builder_image: "registry.redhat.io/rhel10/bootc-image-builder:latest"
    
    # Proxmox Configuration
    pm_host: "pve1"
    pm_vmid: 400 
    pm_storage: "local-lvm"

  tasks:
    # -------------------------------------------------------------------------
    # SECTION 1: REGISTRY PREP & USER BUILD
    # -------------------------------------------------------------------------
    - name: Section 1 - Registry Prep and User Build
      tags: build
      block:
        - name: Login to Quay (User)
          containers.podman.podman_login:
            registry: quay.io
            username: "{{ quay_repo }}"
            password: "{{ vault_quay_token }}"

        - name: Login to Red Hat Registry (User)
          containers.podman.podman_login:
            registry: registry.redhat.io
            username: "{{ vault_rh_username }}"
            password: "{{ vault_rh_password }}"

        - name: Build Bootc Container Image
          containers.podman.podman_image:
            name: "{{ full_image_path }}"
            path: "."
            build:
              file: "{{ containerfile_name }}"
            force: yes

        - name: Push to Quay
          containers.podman.podman_image:
            name: "{{ full_image_path }}"
            push: yes

    # -------------------------------------------------------------------------
    # SECTION 2: ROOT STORAGE SYNC (Ensuring root can see the images)
    # -------------------------------------------------------------------------
    - name: Section 2 - Root Storage Synchronization
      become: true
      tags: sync
      block:
        - name: Login to Registries (Root)
          # Root needs its own auth descriptors in /run/containers/0/auth.json
          containers.podman.podman_login:
            registry: "{{ item.reg }}"
            username: "{{ item.user }}"
            password: "{{ item.pass }}"
          loop:
            - { reg: 'quay.io', user: "{{ quay_repo }}", pass: "{{ vault_quay_token }}" }
            - { reg: 'registry.redhat.io', user: "{{ vault_rh_username }}", pass: "{{ vault_rh_password }}" }

        - name: Clean up existing images in root storage
          shell: "podman image rm -a -f"
          failed_when: false 
          
        - name: Pull Builder and Fresh Image into Root Storage
          containers.podman.podman_image:
            name: "{{ item }}"
            pull: yes
          loop:
            - "{{ builder_image }}"
            - "{{ full_image_path }}"

    # -------------------------------------------------------------------------
    # SECTION 3: IMAGE CONVERSION
    # -------------------------------------------------------------------------
    - name: Section 3 - Image Mode Conversion
      become: true
      tags: convert
      command: >
        podman run --rm --privileged
        -v ./output:/output
        -v /var/lib/containers/storage:/var/lib/containers/storage
        {{ builder_image }}
        --type qcow2 {{ full_image_path }}

    # -------------------------------------------------------------------------
    # SECTION 4: PROXMOX ORCHESTRATION
    # -------------------------------------------------------------------------
    - name: Section 4 - Proxmox Orchestration
      tags: deploy
      block:
        - name: Upload Disk Image to Proxmox via SCP
          shell: >
            scp -o StrictHostKeyChecking=no 
            ./output/qcow2/disk.qcow2 
            root@{{ hostvars['pve1']['ansible_host'] }}:/var/lib/vz/template/qcow/{{ image_name }}.qcow2
          delegate_to: localhost

        - name: Define and Boot VM
          shell: |
            qm stop {{ pm_vmid }} || true
            qm destroy {{ pm_vmid }} || true
            qm create {{ pm_vmid }} --name {{ image_name }} --memory 4096 --cores 2 --cpu host --net0 virtio,bridge=vmbr0 --agent 1
            qm importdisk {{ pm_vmid }} /var/lib/vz/template/qcow/{{ image_name }}.qcow2 {{ pm_storage }}
            qm set {{ pm_vmid }} --scsihw virtio-scsi-pci --scsi0 {{ pm_storage }}:vm-{{ pm_vmid }}-disk-0 --boot "order=scsi0"
            qm start {{ pm_vmid }}
          delegate_to: pve1
          become: false
          vars:
            ansible_connection: ssh

    - name: Section 5 - Cleanup
      tags: cleanup
      become: true
      ansible.builtin.file:
        path: "./output/qcow2/disk.qcow2"
        state: absent
      delegate_to: localhost
